### ISSUE TITLE
VideoReader cannot read demo movie 

### ISSUE THREAD

**Issue by allenleetc** [mathworks/matlab-circleci-orb#29]
Hi,

Thank you for this orb! We have a large MATLAB GUI application and have been trying out CircleCI for automated testing. 

I am up and running with the orb within a Linux executor, and simple MATLAB scripts execute successfully. However, one of our core workflows involves reading movies using VideoReader, and when I try using VideoReader in my test script, I get a harderror. 

Here's my config.yml and test script:

```
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  #welcome: circleci/welcome-orb@0.4.1
  matlab: mathworks/matlab@0.4.0
  
# Orchestrate or schedule a set of jobs
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: videoreadertest
```

```
function videoreadertest(varargin)
mov = 'xylophone.mp4';
which(mov)
vr = VideoReader(mov);
```

And please see attached the error trace. (I've tried a few movies thinking that maybe it was a codec issue but so far all movies cause the error.)
[ml_orb_circleci_videoreader_trace.txt](https://github.com/mathworks/matlab-circleci-orb/files/6907517/ml_orb_circleci_videoreader_trace.txt)

**Comment by mcafaro** [comment]
Hi @allenleetc,

This is likely because MATLAB runs with `-nodisplay`. Can you try reproducing the issue locally by calling `videoreadertest` from a terminal, as shown:

```
$ matlab -nodisplay -batch videoreadertest
```

**Comment by allenleetc** [comment]
Hey @mcafaro,
This seems to run successfully on my ubuntu:
```
al@dl:/dat0/git/APTfork$ /dat0/MATLAB/R2020b/bin/matlab -nodisplay -batch videoreadertest
/dat0/MATLAB/R2020b/toolbox/matlab/audiovideo/xylophone.mp4
```

**Comment by mcafaro** [comment]
Would you mind sharing your repo?

**Comment by allenleetc** [comment]
Sure, it's an OS project. I forked it just to play around with CI:
https://github.com/allenleetc/APT

**Comment by mcafaro** [comment]
It looks like `VideoReader` requires GStreamer on Linux, which is not installed by default on Circle:

https://www.mathworks.com/help/matlab/import_export/supported-video-file-formats.html

You can `apt-get` it in your CircleCI config, as shown:

```yaml
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  #welcome: circleci/welcome-orb@0.4.1
  matlab: mathworks/matlab@0.4.0
  
# Orchestrate or schedule a set of jobs
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: |
          sudo apt-get update -y && sudo apt-get install --no-install-recommends -y libgstreamer1.0-0 \
            gstreamer1.0-tools \
            gstreamer1.0-libav \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly
      - matlab/install
      - matlab/run-command:
          command: videoreadertest
```

You may still run into limitations testing your GUI because MATLAB runs with `-nodisplay` but let us know how it goes.
